
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Dashboard from "@/components/Dashboard";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Home() {


  return (
    <SidebarProvider>
      <AppSidebar />
      <main className=" w-full">
        <SidebarTrigger />
        <section className=" p-8 w-full">
          <Dashboard />
        </section>
      </main>
    </SidebarProvider>
  );
}
